### ISSUE TITLE
「暝霭」之读音

### ISSUE THREAD

**Issue by tusooa** [wmjordan/longyusheng.org#1]
先感谢一下编者，看了好多年了，很受用。

在 /ci/zhoubangyan/2.html 里面，有「暝音鸣，霭音爱」的注解。但查了一些字典，「霭」字都被注为上声（矮），请问这是故意如此呢还是错误呢？

https://www.moedict.tw/%E9%9D%84
https://www.cidianwang.com/cd/m/mingai349165.htm
https://m.gushici.com/ci_c_3221
https://www.baike.com/wikiid/1553940663524867661?from=wiki_content&prd=innerlink&view_id=3q57i0wywc5dkw
https://baike.baidu.com/item/%E9%9C%AD/22617352

最后一个百度百科里，确然在「音韵参考」里有

> [广　韵]：于盖切，去14泰，ài，
> [平水韵]：去声九泰

但是没有写在概述里，文内别处也没有提及。

**Comment by wmjordan** [comment]
谢谢指正！是笔误。

**Comment by wmjordan** [comment]
已修复源代码。
网站和电子书将稍后更新。
